### ISSUE TITLE
Chests with item frames never close :(

### ISSUE THREAD

**Issue by Starkitobonito** [techchrism/container-passthrough#1]
![image](https://user-images.githubusercontent.com/68711129/88446182-6d205480-cded-11ea-90f2-6dd3d8f5d3e4.png)

All the chests with item frames never close.

**Comment by Starkitobonito** [comment]
https://pastebin.com/pUQmhec5 


This appears on the console when I open a chest with item frame

**Comment by techchrism** [comment]
I'm aware of the issue but I believe it's a bug in Spigot, sorry. Nothing in the log file you linked appears to relate to this plugin.
This only applies to double chests, all other containers should be fine.

**Comment by techchrism** [comment]
This is definitely a bug in Spigot and not in the plugin. However, I have added a workaround in the latest version that fixes this issue.
