### ISSUE TITLE
[BUG] Double Chest remains open when leaving inventory w/ Empty Hand

### ISSUE THREAD

**Issue by Zefferis** [techchrism/container-passthrough#2]
Hey there, while running:

ContainerPassthrough v1.2.0 (only active plugin in this test)
on
Paper Build 186 (latest build)

When a player **right clicks** a double chest (normal and trapped) with an **empty hand** the double chest remains in it's "open" graphical state, the chest can be operated with normally, it's a graphical issue - but this only resolves itself when a player moves enough chunks away to unload the area and reload it, F3+A isn't enough to resolve the graphical bug caused by the passthrough

![image](https://user-images.githubusercontent.com/15270437/92539071-3c597a80-f1f5-11ea-8cfb-dc76029568e0.png)

![image](https://user-images.githubusercontent.com/15270437/92540165-9740a100-f1f8-11ea-8dda-024954f145be.png)

Fantastic plugin btw!

EDIT:
Both sides of the chest need to be destroyed before the chests behave normally again, as in the single chest that remains when breaking 1 side of the double chest - remains stuck in it's open state.

**Comment by techchrism** [comment]
Thanks for reporting, I'll test this behavior shortly.
Based on the wording, I assume it only happens with an empty hand and not with an item in the main hand?
Can you check if this still occurs for you on a plain Spigot server and vanilla client?
It was a known bug in the way spigot handled opening double chests and I patched it out manually with reflection but it's likely something has changed.

**Comment by Zefferis** [comment]
> I assume it only happens with an empty hand and not with an item in the main hand?

Yes.

> Can you check if this still occurs for you on a plain Spigot server and vanilla client?

It does, but I use an outdated version of spigot 1.16.2 for testing

```
[19:41:03 INFO]: This server is running CraftBukkit version git-Spigot-379750e-43c7ff9 (MC: 1.16.2) (Implementing API version 1.16.2-R0.1-SNAPSHOT)

[19:41:03 INFO]: Checking version, please wait...

[19:41:03 INFO]: You are 48 version(s) behind
```

**Comment by techchrism** [comment]
I can confirm this is happening on my testing server running the latest paper and vanilla minecraft

**Comment by Zefferis** [comment]
If you need me to do any testing of beta builds feel free to ask ^ ^

**Comment by techchrism** [comment]
The issue should be fixed with the latest release. Thanks again for reporting and offering to test!
