### ISSUE TITLE
chest remains visible open

### ISSUE THREAD

**Issue by paj1s** [techchrism/container-passthrough#6]
When opening a chest through sign after closing it, the chest remains visible as an open chest.

**Comment by techchrism** [comment]
What server version are you running the plugin on?
I test on the latest releases of Paper 1.16 and Spigot 1.17

**Comment by paj1s** [comment]
Latest paper 1.16.5

**Comment by techchrism** [comment]
I was unable to replicate this with Paper 1.16.5 v777 (the current latest) and plugin version 1.2.2
Are you using other plugins that may interfere?

**Comment by paj1s** [comment]
Lockette pro has something to do with chests, i will try it without this plugin.

**Comment by paj1s** [comment]
I tried without it but it has no effect

**Comment by techchrism** [comment]
Are you on the same version of Paper?  Does the problem persist when tested on a server with no other plugins?

**Comment by paj1s** [comment]
Thanks, if it works on your server it must work on mine, i will do some testing.

**Comment by paj1s** [comment]
I tried your newest sunday update and it works, thank you. I thought i already had the newest one but they all have the same name. But anyway it works and im happy.

**Comment by techchrism** [comment]
Great, glad to hear it!
